version: 0.2

env:
  variables:
    BACKEND_REPO: 023036696781.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-backend
    FRONTEND_REPO: 023036696781.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-frontend
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 023036696781.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building backend image...
      - docker build -t $BACKEND_REPO:$IMAGE_TAG ./backend
      - echo Building frontend image...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG ./frontend

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push $BACKEND_REPO:$IMAGE_TAG
      - echo Pushing frontend image...
      - docker push $FRONTEND_REPO:$IMAGE_TAG
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name url-shortener-cluster
      - kubectl rollout restart deployment backend
      - kubectl rollout restart deployment frontend 
      - kubectl apply -f k8s/frontend-service.yaml
      - kubectl apply -f k8s/backend-service.yaml

artifacts:
  files:
    - '**/*'
