apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://panchalharshil18597_db_user:Mr.H3012panchal@url-shortener-cluster.z6pjhky.mongodb.net/url_shortener"